version: '3.8'
services:
  db:
    container_name: postgresql_server
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: license_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5430:5432"

  pgadmin:
    container_name: pgadmin4_server
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: harshilpatel984@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  restapi:
    container_name: license_api_server
    restart: always
    environment:
      ENC_KEY: qc1Un8Utu4wapfMzVcFpo9cXWVRQv6_oFbwQexhV3PM
      APP_PATH: /usr/src/app/data/app
      IMG_PATH: /usr/src/app/data/images
      ORG_DATA_PATH: /usr/src/app/data/license/original_data
      ENC_DATA_PATH: /usr/src/app/data/license/encrypted_data
      CLIENT_ID: 321006c79ba794b84a59522df8600123
      CLIENT_SECRET: 1ea7cb51ebbb80442562b5bedf891f0841f6d8d1
      PAYMENT_URL: https://sandbox.cashfree.com/pg/orders
      DB_IP: db
      DB_PORT: 5430
      DB_NAME: license_db
      DB_USER: root
      DB_PASS: root
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
