version: '3.8'
services:
  db:
    container_name: postgresql_server
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: license_db
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_server
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: harshilpatel984@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  restapi:
    container_name: license_api_server
    build: .
    ports:
      - "8080:8080"
